### Variables
@authUrl = http://localhost:{{$dotenv PORT}}/api/auth 

### Register user
POST {{authUrl}}/register
Content-Type: application/json

{
    "email":"userC@test.com",
    "username":"userC",
    "password":"password"
}

### Login user
POST {{authUrl}}/login
Content-Type: application/json

{
    "username":"userA",
    "password":"password"
}

### Authentication
GET {{authUrl}}/me 
 
### Logout
GET {{authUrl}}/logout 