### Variables
@postUrl = http://localhost:{{$dotenv PORT}}/api/subs 

POST {{postUrl}}
Content-Type: application/json

{
    "name":"flutter", 
    "title":"Flutter 24/7", 
    "description":"Flutter Community"
}