@baseurl = http://localhost:{{$dotenv PORT}}/api/subs

### Get Sub
GET {{baseurl}}/reactjs

### Create Sub
POST {{baseurl}}
Content-Type: application/json

{
    "name": "reactjs",
    "title": "React JS",
    "description": "ReactJS Community"
}
 